from pathlib import Path
from zipfile import ZipFile


class ProjectPackager:
    """
    Creates supporting project files
    and packages the generated backend.
    """

    def package_project(
        self,
        project_directory: Path,
    ) -> Path:
        """
        Create all supporting files
        and return the generated zip file.
        """

        self._create_readme(project_directory)

        self._create_requirements(project_directory)

        self._create_gitignore(project_directory)

        self._create_env_example(project_directory)

        self._create_dockerfile(project_directory)

        self._create_docker_compose(project_directory)

        return self._create_zip(project_directory)

    def _create_readme(
        self,
        project_directory: Path,
    ):

        content = f"""# {project_directory.name}

Generated by APIForge AI.

## Installation

```bash
pip install -r requirements.txt
```
"""
        (project_directory / "README.md").write_text(
            content,
            encoding="utf-8",
        )

    def _create_requirements(
        self,
        project_directory: Path,
    ):

        content = """fastapi
        uvicorn
        sqlalchemy
        pydantic
        pydantic-settings
        pymysql
        python-jose
        python-dotenv
        langchain
        langchain-ollama
        """
        (project_directory / "requirements.txt").write_text(
        content,
        encoding="utf-8",
    )

    def _create_gitignore(
        self,
        project_directory: Path,
    ):

        content = """__pycache__/
        *.pyc
        .env
        venv/
        .idea/
        .vscode/
        """
        (project_directory / ".gitignore").write_text(
            content,
            encoding="utf-8",
        )

    def _create_env_example(
        self,
        project_directory: Path,
    ):

        content = """DB_HOST=localhost
        DB_PORT=3306
        DB_NAME=my_database
        DB_USER=root
        DB_PASSWORD=password

        SECRET_KEY=change_me
        ALGORITHM=HS256
        ACCESS_TOKEN_EXPIRE_MINUTES=30
        """

        (project_directory / ".env.example").write_text(
            content,
            encoding="utf-8",
        )

    def _create_dockerfile(
        self,
        project_directory: Path,
    ):

        content = """FROM python:3.11

    WORKDIR /app

    COPY . .

    RUN pip install -r requirements.txt

    CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    """

        (project_directory / "Dockerfile").write_text(
            content,
            encoding="utf-8",
        )

    def _create_docker_compose(
        self,
        project_directory: Path,
    ):

        content = """version: "3.9"
        services:
        api:
        build: .
        ports:
        - "8000:8000"
        """

        (project_directory / "docker-compose.yml").write_text(
            content,
            encoding="utf-8",
        )

    def _create_zip(
        self,
        project_directory: Path,
    ) -> Path:

        zip_path = project_directory.with_suffix(".zip")

        with ZipFile(zip_path, "w") as zip_file:

            for file in project_directory.rglob("*"):

                if file.is_file():

                    zip_file.write(
                        file,
                        file.relative_to(project_directory),
                    )

        return zip_path

project_packager = ProjectPackager()